from pptx import Presentation
from pptx.util import Inches
import matplotlib.pyplot as plt

# Create presentation
prs = Presentation()

# Slide 1: Title
slide = prs.slides.add_slide(prs.slide_layouts[0])
slide.shapes.title.text = "Client Issue Summary Report"
slide.placeholders[1].text = "Generated using GenSight"

# Slide 2: Summary Insights
summary_text = (
    "Weekly Operational Summary\n"
    "- Peak Issue Day: August 08, 2025 — 13 issues\n"
    "- Average Daily Issues: 6.1\n"
    "- Peak Issue Week: Week of August 18, 2025 — 37 issues\n"
    "- Average Weekly Issues: 25.6\n"
    "- Most Frequent Issue: Non-Compliant Prohance software (9 times)\n"
    "- Top Engineer: Jagadish (66 issues resolved)\n\n"
    "*Auto-generated by GenSight for operational transparency.*"
)
slide = prs.slides.add_slide(prs.slide_layouts[1])
slide.shapes.title.text = "Summary Insights"
slide.placeholders[1].text = summary_text

# Slide 3: GenAI Insights
slide = prs.slides.add_slide(prs.slide_layouts[1])
slide.shapes.title.text = "GenAI Insights"
slide.placeholders[1].text = (
    "GenAI models identified trends in issue types, engineer responsiveness, and resolution efficiency. "
    "Recurring issues suggest automation opportunities. Performance metrics highlight top contributors."
)

# Slide 4: Fine-Tuned Model Recommendations
slide = prs.slides.add_slide(prs.slide_layouts[1])
slide.shapes.title.text = "Fine-Tuned Model Recommendations"
slide.placeholders[1].text = (
    "Recommendations:\n"
    "- Automate high-frequency issues\n"
    "- Reallocate engineers based on workload\n"
    "- Predict recurring problems\n"
    "- Use GenAI summaries in daily standups"
)

# Function to add image slides
def add_image_slide(title, image_path):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    slide.shapes.add_picture(image_path, Inches(1), Inches(1.5), width=Inches(8), height=Inches(4.5))

# Add image slides (replace with actual paths)
add_image_slide("Daily Summary", "daily_summary.png")
add_image_slide("Weekly Summary", "weekly_summary.png")
add_image_slide("Common Issues", "common_issues.png")
add_image_slide("Engineer Workload", "engineer_workload.png")

# Save presentation
prs.save("client_presentation_simple.pptx")
print("✅ Saved as client_presentation_simple.pptx")
